#!/usr/bin/with-contenv sh
# shellcheck shell=sh
export QBT_PROFILE=${CONFIG_DIR}

# wait for VPN connection
until ifconfig | grep tun | grep -q "00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00"; do
    sleep 0.5
done

for rule in "OUTPUT -p udp -d ${DNS} --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT" "INPUT -p udp -s ${DNS} --sport 53 -m state --state ESTABLISHED -j ACCEPT" "OUTPUT -p tcp -d ${DNS} --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT" "INPUT -p tcp -s ${DNS} --sport 53 -m state --state ESTABLISHED -j ACCEPT"; do
    # drop rule if it exists
    if iptables -C "${rule}" >/dev/null 2>&1; then
        echo "dropping IPtables rule: ${rule}"
        iptables -D "${rule}"
    fi
done

umask "${UMASK_SET:-002}"
exec s6-setuidgid "${PUID}:${PGID}" /usr/bin/nzbget/nzbget -s -o outputmode=log -o LogFile="/config/nzbget.log" -o DestDir="/downloads" -o TempDir="/downloads/tmp" -o QueueDir="/downloads/nzbqueue" -o NzbDir="/downloads/nzbs"
